# Generated by Django 5.0.6 on 2024-06-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_profilemodel_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="github",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="linkedin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
