# Generated by Django 4.1.7 on 2024-06-07 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("buildcv", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="educationmodel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="jobpositionmodel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="projectmodel",
            name="user",
        ),
        migrations.DeleteModel(
            name="CompetencyModel",
        ),
        migrations.DeleteModel(
            name="EducationModel",
        ),
        migrations.DeleteModel(
            name="JobPositionModel",
        ),
        migrations.DeleteModel(
            name="ProjectModel",
        ),
    ]
