# Generated by Django 5.0.6 on 2024-06-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buildcv", "0004_cvcreationprocess_summary_guidance"),
    ]

    operations = [
        migrations.CreateModel(
            name="CvTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("template_file", models.FileField(upload_to="cv_templates/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
