# Generated by Django 5.0.6 on 2024-07-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buildcv", "0005_cvtemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="is_freelance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="requisition_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
