# Generated by Django 5.0.6 on 2024-07-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buildcv", "0006_jobpost_is_freelance_jobpost_requisition_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="rejected",
            field=models.BooleanField(default=False),
        ),
    ]
