# Generated by Django 5.0.6 on 2024-07-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buildcv", "0007_jobpost_rejected"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
