# Generated by Django 5.0.6 on 2024-07-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buildcv", "0008_jobpost_deadline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpost",
            name="rejected",
        ),
        migrations.AddField(
            model_name="jobpost",
            name="state",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("draft", "Draft"),
                    ("applied", "Applied"),
                    ("in_process", "In Process"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
