# Generated by Django 5.0.6 on 2024-06-12 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon_image_url", models.URLField(blank=True, null=True)),
                ("provider_name", models.CharField(max_length=50, unique=True)),
                ("provider_url", models.URLField(blank=True, null=True)),
                (
                    "api_endpoint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint_name", models.TextField()),
                ("endpoint_url", models.TextField()),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                            ("UPDATE", "UPDATE"),
                        ],
                        default="GET",
                        max_length=10,
                    ),
                ),
                (
                    "api_type",
                    models.CharField(
                        choices=[
                            ("OauthRest", "OauthRest"),
                            ("OauthGraphql", "OauthGraphql"),
                            ("TokenRest", "TokenRest"),
                        ],
                        default="OauthRest",
                        max_length=15,
                    ),
                ),
                (
                    "data_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoints",
                        to="dataproviders.dataprovider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HttpConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", models.JSONField(blank=True, null=True)),
                ("url_encoded_params", models.JSONField(blank=True, null=True)),
                ("body_type", models.TextField(blank=True, null=True)),
                ("body_content", models.TextField(blank=True, null=True)),
                ("request_type", models.TextField(blank=True, null=True)),
                (
                    "data_provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="http_config",
                        to="dataproviders.dataprovider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OauthConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authorize_url", models.TextField()),
                ("access_token_url", models.TextField()),
                ("client_id", models.TextField()),
                ("client_secret", models.TextField()),
                ("scope", models.JSONField()),
                (
                    "data_provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_config",
                        to="dataproviders.dataprovider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataProviderUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=255)),
                (
                    "refresh_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("token_type", models.CharField(blank=True, max_length=32, null=True)),
                ("expires_in", models.IntegerField(blank=True, null=True)),
                ("data_fetching_is_active", models.BooleanField(default=True)),
                (
                    "data_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dataproviders.dataprovider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_related_name": "data_provider_users",
                "unique_together": {("data_provider", "user")},
            },
        ),
    ]
