# Generated by Django 5.0.6 on 2024-06-08 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cv_content",
            "0002_remove_competencymodel_id_remove_educationmodel_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmodel",
            name="last_updated",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 6, 8, 16, 10, 52, 570808, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
